/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* Define if building for ARM */
/* #undef CPU_ARM */

/* Define if building for MIPS */
/* #undef CPU_MIPS */

/* Define if building for X86 */
#if __LITTLE_ENDIAN__
# define CPU_X86
#endif

/* Define to enable assembly optimizations */
/* #undef ENABLE_ASM */

/* Define to enable FRW optimization */
/* #undef ENABLE_FRW */

/* Define to use SSE2 instructions */
/* #undef ENABLE_SSE2 */

/* Define to use SSE4 instructions */
/* #undef ENABLE_SSE4 */

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `lseek64' function. */
/* #undef HAVE_LSEEK64 */

/* Define to 1 if you have the `malloc' function. */
#define HAVE_MALLOC 1

/* Define to 1 if you have the `memcpy' function. */
#define HAVE_MEMCPY 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the `memset' function. */
#define HAVE_MEMSET 1

/* Define to 1 if you have the `read' function. */
#define HAVE_READ 1

/* Define to 1 if you have the <setjmp.h> header file. */
#define HAVE_SETJMP_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the `write' function. */
#define HAVE_WRITE 1

/* Name of package */
#define PACKAGE "libtta"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "info@true-audio.com"

/* Define to the full name of this package. */
#define PACKAGE_NAME "libtta"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "libtta 2.1"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "libtta"

/* Define to the version of this package. */
#define PACKAGE_VERSION "2.1"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "2.1"

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to `__inline__' or `__inline' if that's what the C compiler
   calls it, or to nothing if 'inline' is not supported under any name.  */
#ifndef __cplusplus
/* #undef inline */
#endif
