/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Name of package */
#define PACKAGE "cuetools"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "sorensen@users.berlios.de"

/* Define to the full name of this package. */
#define PACKAGE_NAME "cuetools"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "cuetools 1.3.1"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "cuetools"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.3.1"

/* Version number of package */
#define VERSION "1.3.1"

/* Define to 1 if `lex' declares `yytext' as a `char *' by default, not a
   `char[]'. */
#define YYTEXT_POINTER 1
